---
- name: create alarm
  ec2_metric_alarm:
    state: present
    region: "{{ region }} 
    name: "cpu-low"
    metric: "CPUUtilization"
    namespace: "AWS/EC2"
    statistic: Average
    comparison: ">="
    threshold: 70.0
    period: 300
    evaluation_periods: 1
    unit: "Percent"
    description: "This will alarm when a bamboo slave's cpu usage average is lower than 5% for 15 minutes "
