--- 
    - name: Creating Autoscaling Group
      ec2_asg:
         name: "{{asgname}}"
         load_balancers: ['{{loadbalancer}}'] 
         availability_zones: [ 'us-west-1a', 'us-west-1c'] 
         launch_config_name: "{{lcname}}"
         min_size: 1
         max_size: 3
         desired_capacity: 1
         vpc_zone_identifier: ['subnet-1ca31e79','subnet-ef5dafb6'] 
