---
  - ec2_lc:
      name: "{{lcname}}"
      image_id: "{{ami}}"
      key_name: "{{keyname}}"
      security_groups: ['sg-9b5e1ffe','sg-b6f0edd3']
      instance_type: "{{instancetype}}"
      state: present
      volumes:
      - device_name: /dev/sda1
        volume_size: 8
        device_type: gp2
        delete_on_termination: true

